### ISSUE TITLE
unknown url type

### ISSUE THREAD

**Issue by TylonHH** [fraschetti/Octoslack#130]
Hi,
I use this plugin with OctoPrint and Pushover. For the snapshor URL I use this link: 192.168.178.96/webcam/?action=stream
It works but it also say "unknown url type". How can I solve this?
Best regards

**Comment by fraschetti** [comment]
Hi @TylonHH 

I'm just triaging bugs at the moment so I don't have my OctoPrint setup accessible.
That said, ?action=steam is going to try to actually grab the MJPG video as opposed to just an image. Instead, you can try ?action=snapshot

Assuming you're using the local stream setup by something like the OctoPi image, your URL for local would actually be:
http://127.0.0.1:8080/?action=snapshot

Otherwise looking at the sample you gave, it would be:
192.168.178.96/webcam/?action=snapshot

This should fix you up. Feel free to reopen this issue if that doesn't solve your problem.
