### ISSUE TITLE
How to backup settings? Where stored?

### ISSUE THREAD

**Issue by TylonHH** [fraschetti/Octoslack#131]
Hi,
as I use multiple printers for this plugin I like to know where the settings are stored? So I can easily c/p this to other machines.
cheers

**Comment by fraschetti** [comment]
Hi @TylonHH 

The answer really depends on what operating system you're using and how you installed OctoPrint.
The short answer (for me) is that plugin settings are stored in the same config.yaml OctoPrint itself uses to store its own settings.
You can find the relevant doc here: https://docs.octoprint.org/en/master/configuration/config_yaml.html

Backing up just the configuration settings for a specific plugin (OctoSlack or otherwise) is a "simple" matter of ripping out the relevant yaml section but ensuring you drop it correctly into the new config yaml on your new system may be a bit tricky if you're not familiar with the format.

Best of luck and feel free to reopen this issue if you find something OctoSlack specific that needs additional attention or discussion.
