### ISSUE TITLE
Any development activity 

### ISSUE THREAD

**Issue by TheLion** [fraschetti/Octoslack#134]
Is this plugin still actively being developed en supported?

None of the issues raised in the last 6 months, have received any reply.

**Comment by fraschetti** [comment]
Hi @TheLion  

The obvious answer is "no" because clearly, I haven't touched this project in a while. That said, I'm finally back to a position where I can spend some cycles here so regardless of whether or not you're still interested in the plugin, I'll be putting in some work toward catching up on the backlog here.
