### ISSUE TITLE
Rotation on webcam image is not done 

### ISSUE THREAD

**Issue by arthurlutz** [fraschetti/Octoslack#2]
(first off, thanks for this plugin it's really cool)

The images sent via imgur are not rotated according to the settings. In the octoprint web interface (under the control tab) the image is correct, but over in slack the image is upside down. In my case both "Flip webcam horizontally" and "Flip webcam vertically" are ticked and enabled.

**Comment by fraschetti** [comment]
Fixed in 1.1.0 - for the camera associated with OctoPrint, the image adjustment settings will be applied via Octoslack. For the additional snapshot images, currently we'll need to rely on the individual camera streams to do the appropriate adjustments. If we find that relying on the cameras to do the adjustments as a limitation, let me know and we can consider doing the adjustments for the additional cameras/snapshots as well (each would need its own configuration of course).
