### ISSUE TITLE
[doc] document where images for imgur are send / stored / accessible

### ISSUE THREAD

**Issue by arthurlutz** [fraschetti/Octoslack#3]
It's great that we can choose between no picture, images on imgur or amazon S3. I'm trying out octoslack with an imgur account, it works great. 

It would be nice to have a little more documentation on where the photos on imgur are stored, if they are public, unlisted, etc. I don't seem them on my profile page. The URLs generated in slack are http://i.imgur.com/randomlettersandnumbers.jpg which seems to indicate they can't be found.

**Comment by fraschetti** [comment]
Previous to 1.1.0 (which I've just published), Imgur uploads are dropped into a generic 'anonymous' album not associated with any of your albums. 1.1.0 will now allow you to grant access to Octoslack so that it can upload images into an Imgur album of your choice.

Please feel free to reopen this issue if that does not solve your issue/concern.
